[package]
name = "list-secrets"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
azure_identity = "0.30.0"
azure_security_keyvault_secrets = "0.9.0"
futures = "0.3.31"
tokio = { version = "1.49.0", features = ["macros"] }
